# Generated by Django 3.2.5 on 2022-04-23 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('u_name', models.TextField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('test_id', models.IntegerField(primary_key=True, serialize=False)),
                ('u_name', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testing.user')),
            ],
            options={
                'db_table': 'testing',
            },
        ),
    ]
