# Generated by Django 4.0.4 on 2022-04-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('u_name', models.TextField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
